<?php
/**
 * AdditionalDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API Retail Procurement Payments Model
 *
 * These APIs allow programmatic access to vendors payments data.
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * AdditionalDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description A field where selling party can provide additional information for tax related or any other purposes.
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdditionalDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdditionalDetails"
     */
    public function testAdditionalDetails()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "detail"
     */
    public function testPropertyDetail()
    {
    }

    /**
     * Test attribute "language_code"
     */
    public function testPropertyLanguageCode()
    {
    }
}
