<?php
/**
 * ScheduledDeliveryShipmentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Direct Fulfillment Orders
 *
 * Provides programmatic access to Direct Fulfillment Vendor's Order data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * ScheduledDeliveryShipmentTest Class Doc Comment
 *
 * @category    Class
 * @description Dates for the Scheduled Delivery Shipments
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduledDeliveryShipmentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ScheduledDeliveryShipment"
     */
    public function testScheduledDeliveryShipment()
    {
    }

    /**
     * Test attribute "scheduled_delivery_service_type"
     */
    public function testPropertyScheduledDeliveryServiceType()
    {
    }

    /**
     * Test attribute "earliest_nominated_delivery_date"
     */
    public function testPropertyEarliestNominatedDeliveryDate()
    {
    }

    /**
     * Test attribute "latest_nominated_delivery_date"
     */
    public function testPropertyLatestNominatedDeliveryDate()
    {
    }
}
