<?php
/**
 * ShipmentDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Direct Fulfillment Orders
 *
 * Provides programmatic access to Direct Fulfillment Vendor's Order data.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * ShipmentDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentDetails information required for the shipment.
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShipmentDetails"
     */
    public function testShipmentDetails()
    {
    }

    /**
     * Test attribute "is_priority_shipment"
     */
    public function testPropertyIsPriorityShipment()
    {
    }

    /**
     * Test attribute "is_scheduled_delivery_shipment"
     */
    public function testPropertyIsScheduledDeliveryShipment()
    {
    }

    /**
     * Test attribute "is_pslip_required"
     */
    public function testPropertyIsPslipRequired()
    {
    }

    /**
     * Test attribute "is_gift"
     */
    public function testPropertyIsGift()
    {
    }

    /**
     * Test attribute "ship_method"
     */
    public function testPropertyShipMethod()
    {
    }

    /**
     * Test attribute "shipment_dates"
     */
    public function testPropertyShipmentDates()
    {
    }

    /**
     * Test attribute "message_to_customer"
     */
    public function testPropertyMessageToCustomer()
    {
    }
}
