<?php
/**
 * ShippingLabelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Provides programmatic access to Vendor for Direct Fulfillment Shipping data
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * ShippingLabelTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingLabel
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingLabelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShippingLabel"
     */
    public function testShippingLabel()
    {
    }

    /**
     * Test attribute "purchase_order_number"
     */
    public function testPropertyPurchaseOrderNumber()
    {
    }

    /**
     * Test attribute "selling_party"
     */
    public function testPropertySellingParty()
    {
    }

    /**
     * Test attribute "ship_from_party"
     */
    public function testPropertyShipFromParty()
    {
    }

    /**
     * Test attribute "label_format"
     */
    public function testPropertyLabelFormat()
    {
    }

    /**
     * Test attribute "label_data"
     */
    public function testPropertyLabelData()
    {
    }
}
