<?php
/**
 * ShipmentMeasurementsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amazon Selling Partner API Retail Procurement Shipment Model
 *
 * Provides programmatic access to Vendor for Retail Procurement Shipping data
 *
 * OpenAPI spec version: v1
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * ShipmentMeasurementsTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentMeasurements
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentMeasurementsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShipmentMeasurements"
     */
    public function testShipmentMeasurements()
    {
    }

    /**
     * Test attribute "gross_shipment_weight"
     */
    public function testPropertyGrossShipmentWeight()
    {
    }

    /**
     * Test attribute "shipment_volume"
     */
    public function testPropertyShipmentVolume()
    {
    }

    /**
     * Test attribute "carton_count"
     */
    public function testPropertyCartonCount()
    {
    }

    /**
     * Test attribute "pallet_count"
     */
    public function testPropertyPalletCount()
    {
    }
}
