<?php
/**
 * StatusUpdateDetailsShipmentScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Provides programmatic access to Vendor for Direct Fulfillment Shipping data
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * StatusUpdateDetailsShipmentScheduleTest Class Doc Comment
 *
 * @category    Class
 * @description These fields are expected when the shipment is a scheduled delivery shipment. In case the shipment is not for a scheduled delivery, this should not be included in the message.
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatusUpdateDetailsShipmentScheduleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StatusUpdateDetailsShipmentSchedule"
     */
    public function testStatusUpdateDetailsShipmentSchedule()
    {
    }

    /**
     * Test attribute "estimated_delivery_date_time"
     */
    public function testPropertyEstimatedDeliveryDateTime()
    {
    }

    /**
     * Test attribute "appt_window_start_date_time"
     */
    public function testPropertyApptWindowStartDateTime()
    {
    }

    /**
     * Test attribute "appt_window_end_date_time"
     */
    public function testPropertyApptWindowEndDateTime()
    {
    }
}
