<?php
/**
 * SubmitShipmentStatusUpdatesResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ClouSale\AmazonSellingPartnerAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Direct Fulfillment Shipping
 *
 * Provides programmatic access to Vendor for Direct Fulfillment Shipping data
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ClouSale\AmazonSellingPartnerAPI;

/**
 * SubmitShipmentStatusUpdatesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The schema for response to a submitShipmentStatusUpdates request.
 * @package     ClouSale\AmazonSellingPartnerAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubmitShipmentStatusUpdatesResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SubmitShipmentStatusUpdatesResponse"
     */
    public function testSubmitShipmentStatusUpdatesResponse()
    {
    }

    /**
     * Test attribute "payload"
     */
    public function testPropertyPayload()
    {
    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {
    }
}
